version: '3.4'

services:
  blogpost:
    image: blogpost
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn backend_blog_post.apps/base:app --host 0.0.0.0 --port 8000"]
    ports:
      - 8000:8000
      - 5678:5678
